### ISSUE TITLE
Convert to CustomTkinter

### ISSUE THREAD

**Issue by khlmood** [adilaxmdv/WeatherApp#6]
I forked your rep and before starting I noticed that no matter what I input in the inputBox I always get the same response: Incorrect place name. Please, correct it. You might need to take a look at your code and update it.  (I also tried using the city in the demo: New York)

**Comment by adilaxmdv** [comment]
![image](https://user-images.githubusercontent.com/74068841/224557801-2219f8f7-b173-4cc8-9208-e8a90105023e.png)

No response. but if you can send a screenshot I can look

**Comment by khlmood** [comment]
I don't think a screenshot can help in any way but here it is
![image](https://user-images.githubusercontent.com/99619908/224565753-c20201cb-5180-4261-8a80-2da09d4fbe99.png)
No matter what I input it doesn't work, maybe the website you are requesting data from change the response format  depending on the I.P/continent of the client network.
(I changed the print statement so it is more clear)

**Comment by adilaxmdv** [comment]
It's interesting if your are okay come discord speak about this 
Discord Name : A D I L#7219
